### PR TITLE
validate-collection.sh: ignore ERROR

### PR DESCRIPTION
**Pull request by goneri**
Ignore errors until https://github.com/ansible/ansible-zuul-jobs/issues/934 is fixed.

### CODE REVIEW

**Comment by goneri** [comment]
@pabelanger can I have your opinion on this? This would really be helpful since:
- we've currently got 4 collections broken because of this problem
- the problem is reported upstream anyway: https://issues.redhat.com/browse/AAH-650
- `galaxy-importer` actually ignore the problem, so can still push new release even if some fragments are unreachable
- all the affected collections already test `ansible-doc` through the sanity several times.

**Comment by pabelanger** [comment]
I would much rather the jobs be moved to non-voting, we want to gate this for other collections which are not affected.  We did this before, and actually problems with our collections slipped though blocking our certification process

**Comment by goneri** [comment]
If we turn on the non-voting flag, we may also miss some problems. I suggest this as an alternative:

`python3 -m galaxy_importer.main community-okd-1.1.3-dev5.tar.gz|grep -v 'unknown doc_fragment'|grep ERROR`

This way we only ignore with well known problem.

**Comment by jillr** [comment]
> If we turn on the non-voting flag, we may also miss some problems. I suggest this as an alternative:
> 
> `python3 -m galaxy_importer.main community-okd-1.1.3-dev5.tar.gz|grep -v 'unknown doc_fragment'|grep ERROR`
> 
> This way we only ignore with well known problem.

Won't we also need to do this with community.aws?

**Comment by pabelanger** [comment]
The issue with any change, is it will affect any other collect that is working. Which I'd prefer not to do.

I think the better solution, is for affect collections to create their own job, that parents to the existing ansible-galaxy-importer. Then, pass your own validate-collection.sh script for the moment.

In parallel, we should raise this issue with galaxy team, saying it's now impacting us, and for them to priorities the fix.

Looking at the code for galaxy-importer, we should be able to pass our own COLLECTION_PATH to it.

**Comment by goneri** [comment]
> > If we turn on the non-voting flag, we may also miss some problems. I suggest this as an alternative:
> > `python3 -m galaxy_importer.main community-okd-1.1.3-dev5.tar.gz|grep -v 'unknown doc_fragment'|grep ERROR`
> > This way we only ignore with well known problem.
> 
> Won't we also need to do this with community.aws?

Oh sorry for the lack of clarity, this was just an example :-). I just mean, we can filter the `unknown doc_fragment` lines from the output.

**Comment by goneri** [comment]
> In parallel, we should raise this issue with galaxy team, saying it's now impacting us, and for them to priorities the fix.

The issue is here: https://issues.redhat.com/browse/AAH-650

**Comment by pabelanger** [comment]
> > In parallel, we should raise this issue with galaxy team, saying it's now impacting us, and for them to priorities the fix.
> 
> The issue is here: [issues.redhat.com/browse/AAH-650](https://issues.redhat.com/browse/AAH-650)

Yup, we need to have the team triage it, and commit resources to fix it.  They are responsive, we just need to ensure we raise up the severity of it.

**Comment by goneri** [comment]
> > > In parallel, we should raise this issue with galaxy team, saying it's now impacting us, and for them to priorities the fix.
> > 
> > 
> > The issue is here: [issues.redhat.com/browse/AAH-650](https://issues.redhat.com/browse/AAH-650)
> 
> Yup, we need to have the team triage it, and commit resources to fix it. They are responsive, we just need to ensure we raise up the severity of it.

Yup, don't hesitate to post a comment.

**Comment by goneri** [comment]
So I turn the job non-voting for the two(?) collections that are affected: https://github.com/ansible/ansible-zuul-jobs/pull/943

**Pull request closed without merging**
